//-------------------Login--------------------
export const LOGIN_WITH_PHONE_START = 'LOGIN_WITH_PHONE_START';
export const LOGIN_WITH_PHONE_SUCCESS = 'LOGIN_WITH_PHONE_SUCCESS';
export const LOGIN_WITH_PHONE_ERROR = 'LOGIN_WITH_PHONE_ERROR';

export const LOGIN_WITH_GOOGLE_START = 'LOGIN_WITH_GOOGLE_START';
export const LOGIN_WITH_GOOGLE_SUCCESS = 'LOGIN_WITH_GOOGLE_SUCCESS';
export const LOGIN_WITH_GOOGLE_ERROR = 'LOGIN_WITH_GOOGLE_ERROR';

export const LOGIN_WITH_FACEBOOK_START = 'LOGIN_WITH_FACEBOOK_START';
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'LOGIN_WITH_FACEBOOK_SUCCESS';
export const LOGIN_WITH_FACEBOOK_ERROR = 'LOGIN_WITH_FACEBOOK_ERROR';

export const GET_IDTOKEN_START = 'GET_IDTOKEN_START';
export const GET_IDTOKEN_SUCCESS = 'GET_IDTOKEN_SUCCESS';
export const GET_IDTOKEN_ERROR = 'GET_IDTOKEN_ERROR';

export const FETCH_CHECKADDUSER_START = 'FETCH_CHECKADDUSER_START';
export const FETCH_CHECKADDUSER_SUCCESS = 'FETCH_CHECKADDUSER_SUCCESS';
export const FETCH_CHECKADDUSER_ERROR = 'FETCH_CHECKADDUSER_ERROR';

//------------------User------------------------
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';