//-------------------Login--------------------
export const LOGIN_WITH_PHONE_START = 'LOGIN_WITH_PHONE_START';
export const LOGIN_WITH_PHONE_SUCCESS = 'LOGIN_WITH_PHONE_SUCCESS';
export const LOGIN_WITH_PHONE_ERROR = 'LOGIN_WITH_PHONE_ERROR';

export const LOGIN_WITH_GOOGLE_START = 'LOGIN_WITH_GOOGLE_START';
export const LOGIN_WITH_GOOGLE_SUCCESS = 'LOGIN_WITH_GOOGLE_SUCCESS';
export const LOGIN_WITH_GOOGLE_ERROR = 'LOGIN_WITH_GOOGLE_ERROR';

export const LOGIN_WITH_FACEBOOK_START = 'LOGIN_WITH_FACEBOOK_START';
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'LOGIN_WITH_FACEBOOK_SUCCESS';
export const LOGIN_WITH_FACEBOOK_ERROR = 'LOGIN_WITH_FACEBOOK_ERROR';

export const GET_IDTOKEN_START = 'GET_IDTOKEN_START';
export const GET_IDTOKEN_SUCCESS = 'GET_IDTOKEN_SUCCESS';
export const GET_IDTOKEN_ERROR = 'GET_IDTOKEN_ERROR';

export const FETCH_CHECKADDUSER_START = 'FETCH_CHECKADDUSER_START';
export const FETCH_CHECKADDUSER_SUCCESS = 'FETCH_CHECKADDUSER_SUCCESS';
export const FETCH_CHECKADDUSER_ERROR = 'FETCH_CHECKADDUSER_ERROR';

export const CHECK_USER_SIGNEDIN_START = 'CHECK_USER_SIGNEDIN_START';
export const CHECK_USER_SIGNEDIN_SUCCESS = 'CHECK_USER_SIGNEDIN_SUCCESS';
export const CHECK_USER_SIGNEDIN_ERROR = 'CHECK_USER_SIGNEDIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_FINISH = 'LOGOUT_FINISH';
//------------------User------------------------
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

export const GET_USER_DETAILS_START = 'GET_USER_DETAILS_START';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';

export const UPDATE_USER_DETAILS_INP_VAL_ERR = 'UPDATE_USER_DETAILS_INP_VAL_ERR';
export const UPDATE_USER_DETAILS_START = 'UPDATE_USER_DETAILS_START';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_ERROR = 'UPDATE_USER_DETAILS_ERROR';

export const UPDATE_USER_PHONENUMBER = 'UPDATE_USER_PHONENUMBER';

export const UPDATE_USER_PROF_IMG_START = 'UPDATE_USER_PROF_IMG_START';
export const UPDATE_USER_PROF_IMG_SUCCESS = 'UPDATE_USER_PROF_IMG_SUCCESS';
export const UPDATE_USER_PROF_IMG_ERROR = 'UPDATE_USER_PROF_IMG_ERROR';

export const UPDATE_USER_TANDC_START = 'UPDATE_USER_TANDC_START';
export const UPDATE_USER_TANDC_SUCCESS = 'UPDATE_USER_TANDC_SUCCESS';
export const UPDATE_USER_TANDC_ERROR = 'UPDATE_USER_TANDC_ERROR';


//--------------------Modal----------------------------
export const LOGIN_MODAL_SHOW = 'LOGIN_MODAL_SHOW';
export const LOGIN_MODAL_HIDE = 'LOGIN_MODAL_HIDE';
export const LOADING_MODAL_SHOW = 'LOADING_MODAL_SHOW';

//------------------------Training--------------------------------------
export const TRAINING_GETALL_COURSE_LIST_START = 'TRAINING_GETALL_COURSE_LIST_START';
export const TRAINING_GETALL_COURSE_LIST_SUCCESS = 'TRAINING_GETALL_COURSE_LIST_SUCCESS';
export const TRAINING_GETALL_COURSE_LIST_ERROR = 'TRAINING_GETALL_COURSE_LIST_ERROR';

export const GET_MYCOURSES_START = 'GET_MYCOURSES_START';
export const GET_MYCOURSES_SUCCESS = 'GET_MYCOURSES_SUCCESS';
export const GET_MYCOURSES_ERROR = 'GET_MYCOURSES_ERROR';

export const GET_COURSE_EXERCISES_START = 'GET_COURSE_EXERCISES_START';
export const GET_COURSE_EXERCISES_SUCCESS = 'GET_COURSE_EXERCISES_SUCCESS';
export const GET_COURSE_EXERCISES_ERROR = 'GET_COURSE_EXERCISES_ERROR';

//------------------------Trainer--------------------------------------
export const GET_STAR_TRAINERS_START = 'GET_STAR_TRAINERS_START';
export const GET_STAR_TRAINERS_SUCCESS = 'GET_STAR_TRAINERS_SUCCESS';
export const GET_STAR_TRAINERS_ERROR = 'GET_STAR_TRAINERS_ERROR';

export const GET_FEATURED_TRAINERS_START = 'GET_FEATURED_TRAINERS_START';
export const GET_FEATURED_TRAINERS_SUCCESS = 'GET_FEATURED_TRAINERS_SUCCESS';
export const GET_FEATURED_TRAINERS_ERROR = 'GET_FEATURED_TRAINERS_ERROR';

export const GET_TRAINER_OFTHE_WEEK_START = 'GET_TRAINER_OFTHE_WEEK_START';
export const GET_TRAINER_OFTHE_WEEK_SUCCESS = 'GET_TRAINER_OFTHE_WEEK_SUCCESS';
export const GET_TRAINER_OFTHE_WEEK_ERROR = 'GET_TRAINER_OFTHE_WEEK_ERROR';
